import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getRepurposeDetail } from "@/app/outlier/live-data";
import { BrandLockup } from "@/components/brand";
import { Card, CardHead, Mono, appStyles as s } from "@/components/app/ui";

// Public — not under /outlier, so the auth proxy never touches it, and no
// signed-in session is required. getRepurposeDetail() works unauthenticated
// here because RLS itself grants read access once is_public is true (see
// migration 0013) — there's no separate "public" query to keep in sync.
// The creator/source post are deliberately left out: that data stays
// private to the owner even when the generated script is shared.
export async function generateMetadata(props: PageProps<"/share/repurpose/[id]">): Promise<Metadata> {
  const { id } = await props.params;
  const detail = await getRepurposeDetail(id);
  return {
    title: detail?.isPublic ? `${detail.title} — Outlier` : "Repurpose — Outlier",
    robots: { index: false, follow: false },
  };
}

export default async function PublicRepurposePage(props: PageProps<"/share/repurpose/[id]">) {
  const { id } = await props.params;
  const detail = await getRepurposeDetail(id);
  if (!detail || !detail.isPublic) notFound();

  return (
    <div className="ws">
      <div style={{ maxWidth: 680, margin: "0 auto", padding: "40px 20px 80px", display: "flex", flexDirection: "column", gap: 24 }}>
        <div style={{ display: "flex", alignItems: "center", gap: 12 }}>
          <Link href="/" aria-label="Creos Labs home" style={{ display: "flex" }}>
            <BrandLockup height={22} />
          </Link>
          <span style={{ color: "var(--ws-hairline-strong)", fontSize: 18 }}>/</span>
          <span className={s.disp} style={{ fontSize: 15, letterSpacing: 0 }}>
            Outlier
          </span>
        </div>

        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <Mono className={s.eyebrow}>Repurposed script</Mono>
          <h1 className={s.disp} style={{ margin: 0, fontSize: 40, lineHeight: 0.95 }}>
            {detail.title}
          </h1>
          <p style={{ margin: 0, fontSize: 15, color: "var(--ws-ink-60)", lineHeight: 1.5 }}>A repurposed script generated by Outlier, from creator content intelligence.</p>
        </div>

        <Card>
          <CardHead label="Content" />
          <p style={{ margin: 0, fontSize: 15, lineHeight: 1.5 }}>{detail.topic}</p>
        </Card>

        <Card paper ring>
          <CardHead label="Hook" paper />
          <p style={{ margin: 0, fontSize: 19, fontWeight: 700, lineHeight: 1.35 }}>{detail.hook}</p>
        </Card>

        <div style={{ display: "flex", flexDirection: "column", gap: 12 }}>
          <Mono className={s.cardLabel} style={{ fontSize: 11 }}>
            Script
          </Mono>
          {detail.beats.map((beat, i) => (
            <Card key={`${beat.name}-${i}`} style={{ padding: 18, gap: 8 }}>
              <span style={{ fontSize: 14, fontWeight: 700 }}>{beat.name}</span>
              <span style={{ fontSize: 15, lineHeight: 1.5 }}>{beat.script}</span>
            </Card>
          ))}
        </div>

        <div style={{ paddingTop: 18, borderTop: "1px solid var(--ws-hairline)" }}>
          <Link href="/" style={{ fontSize: 14, fontWeight: 600 }}>
            Made with Outlier by Creos Labs →
          </Link>
        </div>
      </div>
    </div>
  );
}
