import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { getRepurposeDetail } from "@/app/outlier/live-data";

// Public — not under /outlier, so the auth proxy never touches it, and no
// signed-in session is required. getRepurposeDetail() works unauthenticated
// here because RLS itself grants read access once is_public is true (see
// migration 0013) — there's no separate "public" query to keep in sync.
// The creator/source post are deliberately left out: that data stays
// private to the owner even when the generated script is shared.
export async function generateMetadata(props: PageProps<"/share/repurpose/[id]">): Promise<Metadata> {
  const { id } = await props.params;
  const detail = await getRepurposeDetail(id);
  return {
    title: detail?.isPublic ? `${detail.title} — Outlier` : "Repurpose — Outlier",
    robots: { index: false, follow: false },
  };
}

export default async function PublicRepurposePage(props: PageProps<"/share/repurpose/[id]">) {
  const { id } = await props.params;
  const detail = await getRepurposeDetail(id);
  if (!detail || !detail.isPublic) notFound();

  return (
    <div className="ws" data-theme="dark" suppressHydrationWarning>
      <div className="ws-page-in mx-auto px-6 py-[40px]" style={{ maxWidth: 640, background: "var(--ws-ground)", minHeight: "100vh" }}>
        <p className="text-[13px] font-semibold" style={{ color: "var(--ws-ink-45)" }}>
          Creos Labs · Outlier
        </p>

        <h1 className="mt-[16px] text-[24px] font-bold tracking-[-0.02em]" style={{ color: "var(--ws-ink)" }}>
          {detail.title}
        </h1>
        <p className="mt-[8px] text-[12.5px]" style={{ color: "var(--ws-ink-45)" }}>
          A repurposed script generated by Outlier, from creator content intelligence.
        </p>

        <div className="ws-card mt-[24px]" style={{ padding: "16px 18px" }}>
          <p className="ws-eyebrow">CONTENT</p>
          <p className="mt-[6px] text-[13px] leading-[1.5]" style={{ color: "var(--ws-ink)" }}>
            {detail.topic}
          </p>
        </div>

        <div className="mt-[20px]">
          <p className="ws-eyebrow">HOOK</p>
          <div
            className="ws-card mt-[10px]"
            style={{ padding: "16px 18px", background: "var(--ws-accent-tint)", borderColor: "var(--ws-accent-tint-border)" }}
          >
            <p className="text-[14px] font-medium leading-[1.5]" style={{ color: "var(--ws-accent-tint-ink)" }}>
              {detail.hook}
            </p>
          </div>
        </div>

        <div className="mt-[20px]">
          <p className="ws-eyebrow">SCRIPT</p>
          <div className="mt-[10px] flex flex-col gap-[10px]">
            {detail.beats.map((beat, i) => (
              <div key={`${beat.name}-${i}`} className="ws-card" style={{ padding: "14px 16px" }}>
                <span
                  className="font-semibold uppercase"
                  style={{ fontSize: 9.5, letterSpacing: "0.07em", color: "var(--ws-accent-text)" }}
                >
                  {beat.name}
                </span>
                <p className="mt-[6px] text-[13px] leading-[1.5]" style={{ color: "var(--ws-ink)" }}>
                  {beat.script}
                </p>
              </div>
            ))}
          </div>
        </div>

        <div className="mt-[32px] border-t" style={{ borderColor: "var(--ws-hairline)", paddingTop: 18 }}>
          <Link href="/" className="text-[12.5px] font-medium" style={{ color: "var(--ws-accent-text)" }}>
            Made with Outlier by Creos Labs →
          </Link>
        </div>
      </div>
    </div>
  );
}
